import './globals.css'
import { Inter } from 'next/font/google'
import { AiOutlineSearch } from 'react-icons/ai'
import { SlPeople } from 'react-icons/sl'
import Link from 'next/link'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  <html lang="en">
  <body className={inter.className}>{children}
  <div className="fixed bottom-0 left-0 w-full bg-black rounded-t-lg py-3 px-8 flex justify-center items-center gap-8">
  
  <Link href="/">
  <button className="flex items-center justify-center mr-4 font-semibold text-green-400 hover:text-white">
    <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 18V5l12-2v13"></path>
      <circle cx="6" cy="18" r="3"></circle>
      <circle cx="18" cy="16" r="3"></circle>
    </svg>
    <span className="ml-2">Music</span>
  </button>
  </Link>

  <Link href="/search">
  <button className="flex items-center justify-center mr-4 font-semibold text-green-400 hover:text-white">
   <AiOutlineSearch className="w-6 h-6" />
    <span className="ml-2">Search</span>
  </button>
  </Link>

 <Link href="/spotifyp"> 
  <button className="flex items-center justify-center font-semibold text-green-400 hover:text-white">
   <SlPeople className="w-6 h-6" />
    <span className="ml-2">SpotifyP</span>
  </button>
  </Link> 

</div>
</body>
    </html>
  )
}